### PR TITLE
[IMP] l10n_pt_account_invoicexpress: force update of Invx stored Contact details

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by ljsalvatierra-factorlibre** [comment]
Hi @dreispt, if i am not mistaken, the contact gets updated every time an invoice is sent, right?

Also, why do you send non required contact data to the API? Only name and code are required...

https://invoicexpress.com/api-v2/clients/create-4

imagen

**Comment by dreispt** [comment]
Yes. When we weren’t doing it we got invoices for outdated addresses.

**Comment by dreispt** [comment]
What contact data are we missing?

**Comment by ljsalvatierra-factorlibre** [comment]
> Yes. When we weren’t doing it we got invoices for outdated addresses.

Hi @dreispt, thank you for your response.

Ok, instead of updating the contact for each invoice, you could store a hash of the last sent data and compare it every time you send the invoice, so you only make a request to the API when the contact information changes.

> What contact data are we missing?

What i am trying to say is that it is not necessary to send all the contact information, only the `code` and `name`.

**Comment by dreispt** [comment]
I see, you mean avoid unnecessary requests, not really data missing on calls.
What you suggest is more efficient for sure.
It will add more lines of code, but It would be a welcome addition if you want to propose it.

**Comment by dreispt** [comment]
> What i am trying to say is that it is not necessary to send all the contact information, only the code and name.

You need all them it to update any of the elements that may have changed.
I might skip the call entirely if you're sure there are no changes, but that's the improvement you suggested.

**Comment by ljsalvatierra-factorlibre** [comment]
> > What i am trying to say is that it is not necessary to send all the contact information, only the code and name.
> 
> You need all them it to update any of the elements that may have changed. I might skip the call entirely if you're sure there are no changes, but that's the improvement you suggested.

I mean on creation and update, what i see in the API documentation is that only are required `name` and `code`, the rest of the contact information is optional for Invoicexpress. Maybe there is something i am not understanding.

**Comment by dreispt** [comment]
It is optional but you still want to provide it so that the data in the Invoice is complete.
If you want a different behavior, you can extend the partner prepare values method and implement something different.

**Comment by ljsalvatierra-factorlibre** [comment]
> It is optional but you still want to provide it so that the data in the Invoice is complete. If you want a different behavior, you can extend the partner prepare values method and implement something different.

Ok, in some cases having the complete invoice on Odoo is sufficient. Thank you for the help and your time :)

**Pull request merged**
