### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:, although this time I don't fast track because this is a localization repo with its maintainers.

**Comment by dreispt** [comment]
Yes. I'm the only one active here, but not a problem to wait a bit in case someone else wants to give an opinion.

**Comment by dreispt** [comment]
Why is Runbot failing? I can't see the logs - 404 error...

**Comment by pedrobaeza** [comment]
I have restarted the build to see

**Comment by dreispt** [comment]
Trivial change, fast tracking.

**Pull request merged**
